<a href="https://colab.research.google.com/github/alexandergribenchenko/Data_Science_Toolkit/blob/main/Pandas/Agregaciones_por_fecha.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd
import random
import numpy as np

random.seed(42)
np.random.seed(42)

# Generar una lista de fechas aleatorias entre junio y julio de 2023
start_date = pd.to_datetime('2023-06-01')
end_date = pd.to_datetime('2023-07-31')

date_range = pd.date_range(start_date, end_date, freq='D')
random_dates = random.sample(list(date_range), 20)

# Generar una lista de cantidades de vuelos aleatorias
flight_counts = [random.randint(0, 10) for _ in range(20)]

# Crear el DataFrame con las columnas de fecha y cantidad de vuelos
data = {'Fecha': random_dates, 'Cantidad de vuelos': flight_counts}
df = pd.DataFrame(data)

df = df.sort_values(by=['Fecha'], ascending=[True]).reset_index(drop=True)

df

        Fecha  Cantidad de vuelos
0  2023-06-02                   9
1  2023-06-03                   5
2  2023-06-06                   0
3  2023-06-07                   3
4  2023-06-08                   8
5  2023-06-09                   8
6  2023-06-14                   3
7  2023-06-15                  10
8  2023-06-16                   3
9  2023-06-18                   8
10 2023-06-28                   6
11 2023-07-05                   4
12 2023-07-08                   2
13 2023-07-11                   3
14 2023-07-14                   7
15 2023-07-18                   0
16 2023-07-20                   2
17 2023-07-23                   9
18 2023-07-28                   6
19 2023-07-29                   4

In [18]:
df.groupby(pd.Grouper(key='Fecha', freq='W'))['Cantidad de vuelos'].sum().reset_index()

       Fecha  Cantidad de vuelos
0 2023-06-04                  14
1 2023-06-11                  19
2 2023-06-18                  24
3 2023-06-25                   0
4 2023-07-02                   6
5 2023-07-09                   6
6 2023-07-16                  10
7 2023-07-23                  11
8 2023-07-30                  10