<a href="https://colab.research.google.com/github/alexandergribenchenko/Data_Science_Toolkit/blob/main/Pandas/DS_Pandas_02_Aggregations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas agreggations

# 01. gropupby uses

In [ ]:
import pandas as pd

In [ ]:
dict_input = { 'col_01': ['a','b','a','b'],
               'col_02': ['gato','perro','gato','mico'],
               'col_03': [1,5,6,7]
             }

df = pd.DataFrame.from_dict(dict_input)
df

  col_01 col_02  col_03
0      a   gato       1
1      b  perro       5
2      a   gato       6
3      b   mico       7

In [ ]:
df.\
groupby(['col_01', 'col_02'],
  as_index=True
).\
agg(min_col_3=('col_03', 'min'),
    count_col_3=('col_03', 'count'),
    unique_col_2=('col_02', lambda x: x.nunique()),
    conca=('col_02', lambda x: ','.join(x))
).\
sort_values(by=['conca','col_01'],
            ascending=[False,True]
)

               min_col_3  count_col_3  unique_col_2      conca
col_01 col_02
b      perro           5            1             1      perro
       mico            7            1             1       mico
a      gato            1            2             1  gato,gato

In [ ]:
df.\
groupby(['col_01', 'col_02'],
  as_index=False
).\
agg(min_col_3=('col_03', 'min'),
    count_col_3=('col_03', 'count'),
    unique_col_2=('col_02', lambda x: x.nunique()),
    conca=('col_02', lambda x: ','.join(x))
).\
sort_values(by=['conca','col_01'],
            ascending=[False,True]
)

  col_01 col_02  min_col_3  count_col_3  unique_col_2      conca
2      b  perro          5            1             1      perro
1      b   mico          7            1             1       mico
0      a   gato          1            2             1  gato,gato

# 02. Aggregations with dates

In [ ]:
df_monthly_spend_by_company = df_spend_curated.\
    groupby(
        [pd.Grouper(key='ad_spend_dt', freq='M'),
            'company_name'
        ],
        as_index=True
    ).\
    agg(
        sum_ad_spend=('ad_spend', 'sum')
    ).\
    reset_index(
        drop=False
    ).\
    sort_values(
        by=['ad_spend_dt',
            'sum_ad_spend'],
        ascending=[True,
            False]
    )

# 03. pivot uses

In [ ]:
import pandas as pd

In [ ]:
dict_input = {"A": ["foo", "foo", "foo", "foo", "foo",
                         "bar", "bar", "bar", "bar"],
                   "B": ["one", "one", "one", "two", "two",
                         "one", "one", "two", "two"],
                   "C": ["small", "large", "large", "small",
                         "small", "large", "small", "small",
                         "large"],
                   "D": [1, 2, 2, 3, 3, 4, 5, 6, 7],
                   "E": [2, 4, 5, 5, 6, 6, 8, 9, 9]
             }

df = pd.DataFrame.from_dict(dict_input)
df

     A    B      C  D  E
0  foo  one  small  1  2
1  foo  one  large  2  4
2  foo  one  large  2  5
3  foo  two  small  3  5
4  foo  two  small  3  6
5  bar  one  large  4  6
6  bar  one  small  5  8
7  bar  two  small  6  9
8  bar  two  large  7  9

In [ ]:
df.pivot_table(index = ['A','C'], columns=['B'], values =['D','E'], aggfunc ='sum').reset_index()

     A      C    D         E
B              one  two  one   two
0  bar  large  4.0  7.0  6.0   9.0
1  bar  small  5.0  6.0  8.0   9.0
2  foo  large  4.0  NaN  9.0   NaN
3  foo  small  1.0  6.0  2.0  11.0

# 04. Pivot con agregado de columnas

In [4]:
import pandas as pd
import numpy as np

# Crear datos de ejemplo
np.random.seed(0)
data = {
    'probability': np.random.choice([0.25, 0.5, 0.75, 0.9], size=100),
    'fleet_size': np.random.randint(1, 5, size=100),
    'month': np.random.randint(1, 13, size=100),
    'amount': np.random.randint(10, 500, size=100)
}

# Crear DataFrame a partir del diccionario
df_salida = pd.DataFrame(data)
df_salida

    probability  fleet_size  month  amount
0          0.25           2      3      54
1          0.90           3      4     300
2          0.50           1      3     428
3          0.25           4     12      98
4          0.90           1      1      43
..          ...         ...    ...     ...
95         0.25           1     12     103
96         0.75           1      8     389
97         0.90           2      8     248
98         0.50           3      6      97
99         0.25           1      2     170

[100 rows x 4 columns]

In [5]:
df_min_max = df_salida.pivot_table(index = ['fleet_size','month'], columns=['probability'], values =['amount'], aggfunc =['min','max']).reset_index()
df_min_max

            fleet_size month    min                         max                \
                             amount                      amount
probability                    0.25    0.5   0.75    0.9   0.25    0.5   0.75
0                    1     1    NaN    NaN  447.0   43.0    NaN    NaN  447.0
1                    1     2  170.0    NaN    NaN    NaN  332.0    NaN    NaN
2                    1     3    NaN  428.0    NaN    NaN    NaN  428.0    NaN
3                    1     4    NaN   35.0    NaN  392.0    NaN   35.0    NaN
4                    1     5  207.0    NaN    NaN  124.0  207.0    NaN    NaN
5                    1     6  156.0    NaN    NaN  480.0  156.0    NaN    NaN
6                    1     7  184.0    NaN    NaN    NaN  184.0    NaN    NaN
7                    1     8  219.0    NaN  389.0  126.0  219.0    NaN  389.0
8                    1     9    NaN  367.0  300.0  242.0    NaN  367.0  300.0
9                    1    10    NaN  104.0    NaN  174.0    NaN  357.0    NaN
10                   1    11    NaN    NaN    NaN  266.0    NaN    NaN    NaN
11                   1    12  103.0    NaN    NaN    NaN  456.0    NaN    NaN
12                   2     1    NaN  178.0    NaN  378.0    NaN  178.0    NaN
13                   2     3   54.0    NaN    NaN   79.0   54.0    NaN    NaN
14                   2     4    NaN    NaN    NaN  155.0    NaN    NaN    NaN
15                   2     6  386.0    NaN    NaN    NaN  386.0    NaN    NaN
16                   2     7    NaN  302.0  383.0    NaN    NaN  302.0  383.0
17                   2     8    NaN    NaN  283.0  248.0    NaN    NaN  283.0
18                   2     9    NaN    NaN  301.0  369.0    NaN    NaN  301.0
19                   2    10    NaN  382.0    NaN   38.0    NaN  382.0    NaN
20                   2    12  485.0  296.0    NaN   54.0  485.0  415.0    NaN
21                   3     1  301.0    NaN    NaN    NaN  301.0    NaN    NaN
22                   3     3  490.0    NaN    NaN  317.0  490.0    NaN    NaN
23                   3     4    NaN   26.0  146.0  300.0    NaN  339.0  452.0
24                   3     5  264.0    NaN    NaN    NaN  307.0    NaN    NaN
25                   3     6    NaN   97.0  465.0    NaN    NaN  211.0  465.0
26                   3     7  424.0  121.0    NaN  208.0  424.0  121.0    NaN
27                   3     9  350.0  101.0  443.0  143.0  350.0  101.0  443.0
28                   3    10    NaN   12.0    NaN    NaN    NaN  199.0    NaN
29                   3    12    NaN    NaN   39.0    NaN    NaN    NaN  358.0
30                   4     1    NaN    NaN    NaN   53.0    NaN    NaN    NaN
31                   4     2  333.0    NaN    NaN    NaN  333.0    NaN    NaN
32                   4     3   49.0  469.0    NaN    NaN   49.0  469.0    NaN
33                   4     4   73.0    NaN    NaN  265.0   90.0    NaN    NaN
34                   4     5    NaN    NaN  394.0    NaN    NaN    NaN  394.0
35                   4     6  186.0    NaN    NaN    NaN  186.0    NaN    NaN
36                   4     7    NaN    NaN  146.0  406.0    NaN    NaN  146.0
37                   4     8    NaN  116.0    NaN  284.0    NaN  116.0    NaN
38                   4     9    NaN   46.0  355.0  219.0    NaN  351.0  355.0
39                   4    10    NaN    NaN  450.0  263.0    NaN    NaN  450.0
40                   4    11  103.0    NaN  160.0  205.0  103.0    NaN  160.0
41                   4    12   93.0    NaN  139.0    NaN   98.0    NaN  139.0



probability    0.9
0             43.0
1              NaN
2              NaN
3            392.0
4            124.0
5            480.0
6              NaN
7            126.0
8            242.0
9            251.0
10           357.0
11             NaN
12           378.0
13            79.0
14           155.0
15             NaN
16             NaN
17           248.0
18           369.0
19            38.0
20            54.0
21             NaN
22           317.0
23           433.0
24             NaN
25             NaN
26           299.0
27           143.0
28             NaN
29             NaN
30            53.0
31             NaN
32             NaN
33           469.0
34             NaN
35             NaN
36           406.0
37           284.0
38           231.0
39           263.0
40           205.0
41             NaN

In [6]:
df_min_max.columns

MultiIndex([('fleet_size',       '',   ''),
            (     'month',       '',   ''),
            (       'min', 'amount', 0.25),
            (       'min', 'amount',  0.5),
            (       'min', 'amount', 0.75),
            (       'min', 'amount',  0.9),
            (       'max', 'amount', 0.25),
            (       'max', 'amount',  0.5),
            (       'max', 'amount', 0.75),
            (       'max', 'amount',  0.9)],
           names=[None, None, 'probability'])

In [7]:
df_min_max.columns = ['_'.join(filter(None, map(str, col))) for col in df_min_max.columns]

In [8]:
df_min_max.columns

Index(['fleet_size', 'month', 'min_amount_0.25', 'min_amount_0.5',
       'min_amount_0.75', 'min_amount_0.9', 'max_amount_0.25',
       'max_amount_0.5', 'max_amount_0.75', 'max_amount_0.9'],
      dtype='object')

# Bibliography

- [Advanced agragations](https://brettromero.com/pandas-advanced-aggregation/)