<a href="https://colab.research.google.com/github/alexandergribenchenko/Data_Science_Toolkit/blob/main/Pandas/DS_Pandas_02_Aggregations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas agreggations

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df_x = pd.DataFrame(np.random.rand(4,4), columns=list('abcd'))
df_x['perro'] = [0, 0, 1, 1]
df_x['gato'] = ['a', 'b', 'a', 'b']
df_x

          a         b         c         d  perro gato
0  0.981293  0.667100  0.843326  0.147237      0    a
1  0.457039  0.292530  0.742616  0.756142      0    b
2  0.419957  0.879610  0.838128  0.968107      1    a
3  0.176276  0.776043  0.819586  0.677328      1    b

In [ ]:
df_x.groupby(['perro','gato']).agg(
    min_a=('a', 'min'),
    count_a= ('a', 'count'),
    max_b=('b', 'max')
)

               min_a  count_a     max_b
perro gato
0     a     0.981293        1  0.667100
      b     0.457039        1  0.292530
1     a     0.419957        1  0.879610
      b     0.176276        1  0.776043

# Bibliography

- [Advanced agragations](https://brettromero.com/pandas-advanced-aggregation/)